"""
TOOL 2 — places_search

5-8 entries per city per category, each with full address, coordinates,
amenities, reviews, pricing details, policies, nearby transit.
Covers: Paris, Bali, Tokyo, Amsterdam, Germany/Berlin, Dehradun,
Himachal Pradesh/Manali, India/Delhi, Kyoto, Switzerland/Zurich.
"""
from __future__ import annotations


_PLACES_DB: dict[str, dict[str, list[dict]]] = {

    # ── PARIS ─────────────────────────────────────────────────────────────
    "paris": {
        "hotels": [
            {
                "name": "Hôtel du Louvre (Hyatt)",
                "stars": 4, "price_per_night_usd": 285,
                "address": "Place André Malraux, 75001 Paris",
                "coordinates": {"lat": 48.8639, "lon": 2.3356},
                "area": "1st arrondissement — Right Bank",
                "metro": ["Palais Royal–Musée du Louvre (Line 1/7) — 3 min walk"],
                "check_in": "15:00", "check_out": "12:00",
                "amenities": ["Free Wi-Fi", "Fitness centre", "24-hr concierge", "Valet parking €55/night", "Brasserie on-site", "Air conditioning", "Soundproofed rooms", "Safe deposit box"],
                "room_types": {"standard_double": 285, "deluxe_eiffel_view": 390, "junior_suite": 550},
                "reviews": {"tripadvisor_rating": 4.5, "google_rating": 4.4, "total_reviews": 3840, "highlights": ["superb location", "helpful concierge", "Louvre views from upper floors"]},
                "cancellation_policy": "Free cancellation up to 48h before check-in; after that, first night charged.",
                "breakfast": "Continental €28/person or skip and use nearby cafés.",
                "notes": "5-min walk to the Louvre, 12-min walk to the Seine. Excellent base for Right Bank museums.",
            },
            {
                "name": "Le Marais Boutique Hotel",
                "stars": 3, "price_per_night_usd": 162,
                "address": "15 Rue de Bretagne, 75003 Paris",
                "coordinates": {"lat": 48.8624, "lon": 2.3613},
                "area": "3rd arrondissement — Le Marais",
                "metro": ["Filles du Calvaire (Line 8) — 2 min walk", "Temple (Line 3) — 4 min walk"],
                "check_in": "14:00", "check_out": "11:30",
                "amenities": ["Free Wi-Fi", "Courtyard garden", "Espresso maker in room", "Bicycle hire €15/day", "Non-smoking throughout"],
                "room_types": {"cosy_double": 162, "superior_double_garden_view": 195, "family_room": 270},
                "reviews": {"tripadvisor_rating": 4.3, "google_rating": 4.5, "total_reviews": 1210, "highlights": ["cool neighbourhood", "friendly staff", "independent cafes around corner"]},
                "cancellation_policy": "Free cancellation 72h before arrival.",
                "notes": "Heart of the trendy Marais district; walking distance to Centre Pompidou and Place des Vosges.",
            },
            {
                "name": "Grand Hôtel Opéra (InterContinental)",
                "stars": 5, "price_per_night_usd": 510,
                "address": "2 Rue Scribe, 75009 Paris",
                "coordinates": {"lat": 48.8717, "lon": 2.3313},
                "area": "9th arrondissement — Opéra Quarter",
                "metro": ["Opéra (Lines 3/7/8) — 1 min walk"],
                "check_in": "15:00", "check_out": "12:00",
                "amenities": ["Indoor heated pool", "Spa by ESPA", "Fitness centre", "Café de la Paix on-site (Michelin Bib Gourmand)", "24-hr butler", "Free Wi-Fi (1 Gbps)", "Valet parking €75/night", "IHG One Rewards eligible"],
                "room_types": {"classic_room": 510, "superior_room": 650, "junior_suite_eiffel_view": 890, "grand_suite": 1800},
                "reviews": {"tripadvisor_rating": 4.7, "google_rating": 4.6, "total_reviews": 7250},
                "cancellation_policy": "Non-refundable rates available (10% discount); Flex rates free cancellation 24h prior.",
                "notes": "Historic property; Café de la Paix served Émile Zola and Coco Chanel. Opéra Garnier visible from windows.",
            },
            {
                "name": "Ibis Paris Tour Eiffel",
                "stars": 3, "price_per_night_usd": 125,
                "address": "2 Rue Cambronne, 75015 Paris",
                "area": "15th arrondissement — budget-friendly, good transit links",
                "metro": ["Cambronne (Line 6) — 1 min walk"],
                "amenities": ["Free Wi-Fi", "24-hr reception", "Bar", "AC"],
                "room_types": {"standard": 125, "superior": 148},
                "reviews": {"tripadvisor_rating": 4.1, "google_rating": 4.2, "total_reviews": 4100},
                "cancellation_policy": "Free cancellation up to 48h before check-in.",
                "notes": "Best-value chain option; 20 min from city centre by metro.",
            },
        ],
        "restaurants": [
            {
                "name": "Septime",
                "cuisine": "Modern French / Neo-bistro",
                "michelin": "1 star",
                "price_range": "$$$  (avg €75/person without wine)",
                "address": "80 Rue de Charonne, 75011 Paris",
                "area": "11th arrondissement",
                "opening_hours": "Lunch Tue–Fri 12:15–14:00; Dinner Mon–Fri 19:15–21:45; closed Sat–Sun",
                "reservations": "Essential — book 3-4 weeks ahead via website or Resy",
                "dietary": {"vegetarian": "Ask at booking — tasting menu can be adapted", "shellfish": "PRESENT — prominently features in tasting menu; notify allergy at booking"},
                "reviews": {"google_rating": 4.7, "la_liste_rank": 82, "highlights": ["best neo-bistro in Paris", "seasonal tasting menu", "natural wine list"]},
                "notes": "Chef Bertrand Grébaut's landmark restaurant. No à la carte — tasting menu only. Worth every euro.",
            },
            {
                "name": "Chez L'Ami Jean",
                "cuisine": "Basque / South-West French",
                "price_range": "$$ (avg €45/person)",
                "address": "27 Rue Malar, 75007 Paris",
                "area": "7th arrondissement (near Eiffel Tower)",
                "opening_hours": "Tue–Sat 12:00–14:00 and 19:00–23:00; closed Mon & Sun",
                "reservations": "Recommended 1 week ahead",
                "dietary": {"shellfish": "PRESENT — razor clams, prawns on menu; warn on booking", "vegetarian": "Limited options"},
                "reviews": {"google_rating": 4.5, "highlights": ["legendary rice pudding dessert", "jovial atmosphere", "hearty portions"]},
            },
            {
                "name": "Au Passage",
                "cuisine": "Natural wine bistro / small plates",
                "price_range": "$$ (avg €38/person)",
                "address": "1bis Passage Saint-Sébastien, 75011 Paris",
                "opening_hours": "Mon–Sat 18:30–23:30; lunch Fri 12:00–14:30",
                "reservations": "Walk-in friendly at bar; tables bookable via phone",
                "dietary": {"vegetarian": "Good options among small plates", "shellfish": "Occasionally featured — check daily menu"},
            },
            {
                "name": "L'As du Fallafel",
                "cuisine": "Israeli / Falafel street food",
                "price_range": "$ (falafel wrap €7)",
                "address": "34 Rue des Rosiers, 75004 Paris",
                "area": "4th arrondissement — Jewish Quarter of Le Marais",
                "opening_hours": "Mon–Thu 11:00–24:00; Fri 11:00–15:00 (closes before Shabbat); Sun 11:00–24:00",
                "dietary": {"vegetarian": "Fully vegetarian / vegan options", "shellfish": "None", "halal": "No (kosher)"},
                "notes": "Legendary; expect a queue. Worth it.",
            },
        ],
        "attractions": [
            {
                "name": "Musée d'Orsay",
                "type": "Art Museum",
                "entry_usd": 17,
                "address": "1 Rue de la Légion d'Honneur, 75007 Paris",
                "opening_hours": "Tue–Sun 09:30–18:00; Thu until 21:45; closed Mon",
                "highlights": ["Largest Impressionist collection in the world", "Monet, Renoir, Van Gogh, Degas", "The building itself is a Beaux-Arts railway station"],
                "tips": ["Buy timed entry online (Paris Museum Pass accepted)", "Thursday evening is quietest", "Café on top floor has views of Sacré-Cœur"],
                "duration_recommended_hrs": 2.5,
            },
            {
                "name": "Palace of Versailles",
                "type": "Royal Palace and Gardens",
                "entry_usd": 22,
                "address": "Place d'Armes, 78000 Versailles",
                "transport": "RER C from Paris (40 min, €7 round trip)",
                "opening_hours": "Tue–Sun 09:00–18:30 (palace); gardens open daily 08:00–20:30",
                "highlights": ["Hall of Mirrors", "Marie Antoinette's Estate (Petit Trianon)", "2000-acre formal gardens", "Musical fountain shows Sat–Sun (May–Oct, extra charge)"],
                "tips": ["Arrive at opening to beat coach groups", "Hire a golf cart to see the gardens (€32/hr)", "Full day excursion recommended"],
                "duration_recommended_hrs": 6,
            },
            {
                "name": "Eiffel Tower",
                "type": "Landmark",
                "entry_usd": 30,
                "address": "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
                "opening_hours": "Daily 09:00–00:45 (mid-June–Aug); 09:30–23:45 (rest of year)",
                "highlights": ["Top floor views 276m up", "Light show every hour after dusk", "Jules Verne restaurant (Michelin 2-star) on 2nd floor"],
                "tips": ["Book summit tickets online 60+ days ahead in peak season; walk-up stairs to 2nd floor is cheaper & faster"],
                "duration_recommended_hrs": 2,
            },
        ],
    },

    # ── BALI ──────────────────────────────────────────────────────────────
    "bali": {
        "hotels": [
            {
                "name": "Four Seasons Resort Bali at Sayan",
                "stars": 5, "price_per_night_usd": 950,
                "area": "Ubud — jungle and river gorge",
                "address": "Sayan, Ubud, Gianyar, Bali 80571",
                "coordinates": {"lat": -8.5069, "lon": 115.2476},
                "check_in": "15:00", "check_out": "12:00",
                "amenities": ["Jungle canopy infinity pool", "COMO Shambhala-style spa", "Yoga pavilion daily", "Private villa plunge pools (villa category)", "All-day dining overlooking Ayung River", "Complimentary cooking class", "Airport transfer $80 each way", "Free Wi-Fi"],
                "room_types": {"suite": 950, "1br_villa_pool": 1600, "2br_villa_pool": 2900},
                "reviews": {"tripadvisor_rating": 5.0, "conde_nast_traveller": "Gold List", "highlights": ["most romantic resort in Bali", "rice paddy walks at dawn", "extraordinary spa"]},
                "cancellation_policy": "72h cancellation window; some advance rates non-refundable.",
            },
            {
                "name": "Bisma Eight",
                "stars": 4, "price_per_night_usd": 230,
                "area": "Ubud — central, rice terrace views",
                "address": "Jl. Bisma, Ubud, Bali 80571",
                "amenities": ["Infinity pool over rice paddies", "Treetop restaurant", "Free shuttle to Ubud centre", "Spa", "Yoga classes", "Wi-Fi"],
                "room_types": {"forest_suite": 230, "valley_suite": 310, "pool_villa": 520},
                "reviews": {"tripadvisor_rating": 4.7, "highlights": ["exceptional breakfast", "Instagram-worthy pool", "quiet yet walkable to Ubud market"]},
                "cancellation_policy": "Free cancellation 48h before arrival.",
                "notes": "Best mid-range option in Ubud with luxury feel.",
            },
            {
                "name": "Katamama",
                "stars": 5, "price_per_night_usd": 480,
                "area": "Seminyak — beachside",
                "address": "Jl. Petitenget No.51B, Seminyak, Bali 80361",
                "amenities": ["Private beach club access (Potato Head)", "Balinese craft-filled rooms (handmade fabrics, terracotta)", "Antique furnishings sourced from Java", "Rooftop pool", "Shambhala Spa", "In-room bath butler service"],
                "room_types": {"studio_suite": 480, "1br_suite": 750},
                "reviews": {"tripadvisor_rating": 4.8, "highlights": ["unique artisan design", "Potato Head parties", "incredible location"]},
            },
            {
                "name": "Komaneka at Bisma",
                "stars": 5, "price_per_night_usd": 380,
                "area": "Ubud",
                "amenities": ["3 pools", "award-winning Komaneka restaurant", "art gallery", "spa", "rice paddy walking trails from property"],
                "room_types": {"valley_suite": 380, "pool_villa": 680},
                "reviews": {"tripadvisor_rating": 4.9},
            },
            {
                "name": "Legian Kriyamaha Villa",
                "stars": 3, "price_per_night_usd": 95,
                "area": "Legian — budget-friendly, near Kuta beach",
                "amenities": ["Private pool", "Free breakfast", "Wi-Fi", "Free shuttle to beach"],
                "reviews": {"google_rating": 4.6, "highlights": ["exceptional value", "lovely family-run property"]},
                "cancellation_policy": "Free cancellation 24h before check-in.",
            },
        ],
        "restaurants": [
            {
                "name": "Locavore",
                "cuisine": "Modern Indonesian / Farm-to-Table",
                "awards": "Asia's 50 Best Restaurants (ranked #23 2025)",
                "price_range": "$$$ (tasting menu IDR 950 000 / ~$59)",
                "address": "Jl. Dewi Sita No.10, Ubud, Bali 80571",
                "opening_hours": "Lunch Tue–Sat 12:00–15:00; Dinner Mon–Sat 18:30–23:00",
                "reservations": "Book 2-4 weeks ahead; online via locavore.id",
                "dietary": {"shellfish": "PRESENT — seasonal seafood prominently featured; notify for allergy", "vegetarian": "Locavore Next Door next-door is fully plant-based (same team, separate restaurant)"},
                "notes": "Best fine dining in Bali. Hyperlocal ingredients, brilliant cocktail pairing.",
            },
            {
                "name": "Warung Ibu Oka",
                "cuisine": "Balinese suckling pig (Babi Guling)",
                "price_range": "$ (IDR 70 000 / ~$4.50)",
                "address": "Jl. Suweta No.2, Ubud, Bali 80571",
                "opening_hours": "Daily 11:00–17:00 or until sold out",
                "dietary": {"shellfish": "None", "vegetarian": "Not suitable (pork-focused)", "pork": "Pork only restaurant"},
                "notes": "Famous babi guling; referenced in Anthony Bourdain's show. Arrive early — sells out.",
            },
            {
                "name": "Merah Putih",
                "cuisine": "Modern Indonesian — pan-archipelago",
                "price_range": "$$ (avg IDR 350 000 / ~$22)",
                "address": "Jl. Petitenget No.100X, Seminyak, Bali 80361",
                "opening_hours": "Daily 12:00–23:00",
                "dietary": {"shellfish": "PRESENT", "vegetarian": "Good selection of vegetable dishes from Java, Sumatra, Bali traditions"},
            },
        ],
        "attractions": [
            {
                "name": "Tegallalang Rice Terraces",
                "type": "UNESCO-listed natural landscape",
                "entry_usd": 2,
                "address": "Tegallalang Village, Ubud, Gianyar",
                "opening_hours": "Daily 08:00–18:00",
                "highlights": ["Subak irrigation system (UNESCO)", "Sunrise shots world-class", "Swing over the terraces ($10 extra)"],
                "tips": ["Go at 07:30 before tour buses; avoid 10:00–14:00 peak heat and crowds"],
                "duration_recommended_hrs": 1.5,
            },
            {
                "name": "Tanah Lot Temple",
                "type": "Sea Temple",
                "entry_usd": 5,
                "address": "Beraban, Kediri, Tabanan, Bali",
                "opening_hours": "Daily 07:00–19:00",
                "highlights": ["Iconic offshore temple on sea rock", "Spectacular sunset backdrop", "Black-and-yellow sea snakes considered sacred guardians"],
                "tips": ["Arrive 1 hour before sunset", "Accessible only at low tide"],
                "duration_recommended_hrs": 2,
            },
            {
                "name": "Mount Batur Sunrise Trek",
                "type": "Volcano Trek",
                "entry_usd": 65,
                "altitude_m": 1717,
                "highlights": ["Sunrise over Lake Batur", "Active volcano — sometimes see steam vents", "Boil eggs in volcanic steam at summit"],
                "tips": ["Depart hotel 01:30–02:00; summit by 05:30 for sunrise", "Mandatory guide ($30–40) on top of entrance", "Cold at summit — bring fleece"],
                "duration_recommended_hrs": 7,
            },
        ],
    },

    # ── TOKYO ─────────────────────────────────────────────────────────────
    "tokyo": {
        "hotels": [
            {
                "name": "Park Hyatt Tokyo",
                "stars": 5, "price_per_night_usd": 720,
                "area": "Shinjuku — floors 39–52 of Park Tower",
                "address": "3-7-1-2 Nishi-Shinjuku, Shinjuku City, Tokyo 163-1055",
                "coordinates": {"lat": 35.6869, "lon": 139.6908},
                "check_in": "15:00", "check_out": "12:00",
                "amenities": ["New York Bar (Lost in Translation filming location)", "50m heated indoor pool on 47th floor", "Spa", "Free Wi-Fi (1 Gbps)", "Mountain views (clear days: Mt Fuji)", "Andaz Lounge 24-hr"],
                "room_types": {"park_room": 720, "park_deluxe": 920, "park_suite": 1400},
                "reviews": {"tripadvisor_rating": 4.9, "highlights": ["iconic, legendary service", "New York Bar worth every yen", "city views extraordinary"]},
                "cancellation_policy": "Free cancellation 72h before arrival.",
            },
            {
                "name": "Shinjuku Granbell Hotel",
                "stars": 4, "price_per_night_usd": 195,
                "area": "Shinjuku — Golden Gai / Kabukicho proximity",
                "address": "2-14-5 Kabukicho, Shinjuku, Tokyo 160-0021",
                "amenities": ["Designer rooms (each floor different theme)", "Bar on ground floor", "Free Wi-Fi", "Proximity to Golden Gai bars (2 min walk)"],
                "room_types": {"standard_double": 195, "superior_double": 240, "suite": 380},
                "reviews": {"tripadvisor_rating": 4.4, "highlights": ["cool design", "perfect Shinjuku location", "good value for Tokyo"]},
                "cancellation_policy": "Free cancellation 48h before arrival.",
            },
            {
                "name": "Hoshinoya Tokyo",
                "stars": 5, "price_per_night_usd": 580,
                "area": "Otemachi — business district, 10 min from Imperial Palace",
                "amenities": ["Onsen on top floor (rare in central Tokyo)", "Kaiseki dinner ($120/person extra)", "Tea ceremony twice daily", "Tatami rooms", "Japanese bath in every room"],
                "room_types": {"tatami_twin": 580, "tatami_double": 630},
                "reviews": {"tripadvisor_rating": 4.8, "highlights": ["authentic ryokan experience in central Tokyo", "onsen is magical", "exceptional kaiseki"]},
            },
            {
                "name": "Khaosan Tokyo Origami",
                "stars": 2, "price_per_night_usd": 88,
                "area": "Asakusa — traditional neighbourhood",
                "amenities": ["Free Wi-Fi", "Rooftop deck", "Shared kitchen", "Bicycle hire ¥1000/day", "Walking distance to Senso-ji Temple"],
                "room_types": {"dorm_6bed": 35, "private_double": 88, "private_triple": 120},
                "reviews": {"tripadvisor_rating": 4.3, "highlights": ["unbeatable location for temples", "friendly staff", "great social atmosphere"]},
                "cancellation_policy": "Free cancellation 24h before check-in.",
            },
        ],
        "restaurants": [
            {
                "name": "Sukiyabashi Jiro Honten (Jiro Dreams of Sushi)",
                "cuisine": "Omakase sushi",
                "michelin": "3 stars",
                "price_range": "$$$$ (¥40 000 / ~$260 per person — lunch only)",
                "address": "4-2-15 Ginza, Chuo City, Tokyo 104-0061",
                "opening_hours": "Mon–Fri lunch 11:30 only (one seating); closed weekends & Aug",
                "reservations": "Must be made through your hotel concierge ONLY; typically 1-2 months ahead",
                "dietary": {"shellfish": "CENTRAL TO MENU — all courses involve fish and shellfish; not suitable for shellfish allergy", "vegetarian": "Completely unsuitable"},
                "notes": "Obama dined here. 10-seat counter. 20-minute meal. Legendary.",
            },
            {
                "name": "Ichiran Ramen",
                "cuisine": "Hakata tonkotsu ramen — solo dining experience",
                "price_range": "$ (¥980 / ~$6.50)",
                "address": "Multiple locations across Tokyo",
                "opening_hours": "24 hours",
                "dietary": {"shellfish": "Broth is pork-based — no shellfish", "vegetarian": "Not suitable (pork broth)"},
                "notes": "Individual booths, customise your ramen on a form, no social pressure. Tokyo institution.",
            },
            {
                "name": "Gonpachi Nishi-Azabu (Kill Bill restaurant)",
                "cuisine": "Izakaya / traditional Japanese robata",
                "price_range": "$$ (avg ¥4500 / ~$29)",
                "address": "1-13-11 Nishi-Azabu, Minato City, Tokyo 106-0031",
                "opening_hours": "Daily 17:00–04:00",
                "dietary": {"shellfish": "PRESENT on menu — grilled scallops, shrimp skewers; avoid specific dishes", "vegetarian": "Vegetable skewers, tofu dishes available"},
                "notes": "Quentin Tarantino used the interior as inspiration for Kill Bill's Crazy 88 fight scene. Dramatic multilevel interior.",
            },
            {
                "name": "Afuri Ramen",
                "cuisine": "Yuzu shio (citrus salt) ramen",
                "price_range": "$ (¥1200 / ~$8)",
                "address": "Multiple locations — Harajuku, Ebisu, Nakameguro",
                "opening_hours": "Daily 11:00–23:00",
                "dietary": {"shellfish": "None", "vegetarian": "Vegan ramen available (yuzu shio vegan broth)"},
                "notes": "Lighter alternative to tonkotsu. Yuzu aroma is extraordinary.",
            },
            {
                "name": "Tsukiji Outer Market stalls",
                "cuisine": "Fresh seafood breakfast / street food",
                "price_range": "$ (¥200–1500 per item)",
                "address": "4-16-2 Tsukiji, Chuo City, Tokyo 104-0045",
                "opening_hours": "Daily 05:00–14:00 (most stalls); busiest 06:30–09:00",
                "dietary": {"shellfish": "DOMINANT — grilled scallops, oysters, shrimp skewers everywhere; NOT suitable for shellfish allergy", "vegetarian": "Very limited — tamago (egg) stalls only"},
                "notes": "Fish market moved to Toyosu 2018; Tsukiji Outer Market (street food stalls) remains open. An extraordinary food experience.",
            },
        ],
        "attractions": [
            {
                "name": "Senso-ji Temple",
                "type": "Buddhist temple — Tokyo's oldest",
                "entry_usd": 0,
                "address": "2-3-1 Asakusa, Taito City, Tokyo 111-0032",
                "opening_hours": "Main hall 06:00–17:00; grounds always open",
                "highlights": ["Kaminarimon (Thunder Gate) giant lantern", "Nakamise shopping street (200m of traditional stalls)", "Fortune strips (omikuji) from vending machine", "Spectacular at dawn with incense smoke"],
                "tips": ["06:00–07:30 is magical; tour buses arrive 09:30+", "Rent kimono nearby (¥3000/half day)"],
            },
            {
                "name": "TeamLab Borderless",
                "type": "Digital art museum",
                "entry_usd": 38,
                "address": "New location: Azabudai Hills, Minato City, Tokyo (opened 2024)",
                "opening_hours": "Daily 09:00–22:00 (last entry 20:00)",
                "highlights": ["60+ immersive digital art rooms", "Flower Forest, Crystal World, Light Sculpture Forest", "No fixed route — different each visit"],
                "tips": ["Book online; sell out 2-3 weeks ahead in peak season", "Wear comfortable shoes — lots of walking"],
                "duration_recommended_hrs": 3,
            },
        ],
    },

    # ── AMSTERDAM ─────────────────────────────────────────────────────────
    "amsterdam": {
        "hotels": [
            {
                "name": "Pulitzer Amsterdam",
                "stars": 5, "price_per_night_usd": 420,
                "area": "Canal Ring — 25 interconnected 17th-century canal houses",
                "address": "Prinsengracht 315-331, 1016 GZ Amsterdam",
                "coordinates": {"lat": 52.3746, "lon": 4.8832},
                "amenities": ["Pulitzer's Bar (garden terrace on canal)", "Private boat tours from hotel jetty", "Bikes included", "Spa", "Free Wi-Fi", "Bookable canal-view rooms"],
                "room_types": {"classic": 420, "canal_view_superior": 590, "suite": 980},
                "reviews": {"tripadvisor_rating": 4.7, "highlights": ["most romantic hotel in Amsterdam", "bikes on loan", "canal views from every room"]},
                "cancellation_policy": "Free cancellation 48h before check-in.",
                "notes": "UNESCO World Heritage canal ring location. Exceptional for honeymooners or special occasions.",
            },
            {
                "name": "Hotel V Nesplein",
                "stars": 4, "price_per_night_usd": 195,
                "area": "Centrum — Old Centre, near Dam Square and Jordaan",
                "address": "Nes 49, 1012 KD Amsterdam",
                "amenities": ["Lively bar/restaurant on-site", "Bikes to rent (€15/day)", "Free Wi-Fi", "Modern Dutch design interior"],
                "room_types": {"standard": 195, "superior": 240},
                "reviews": {"tripadvisor_rating": 4.5, "highlights": ["brilliant central location", "social bar", "great value for Amsterdam"]},
                "cancellation_policy": "Free cancellation 72h before arrival.",
            },
            {
                "name": "Generator Amsterdam",
                "stars": 3, "price_per_night_usd": 45,
                "area": "Oost (East) — 15 min tram from centre",
                "amenities": ["Lively bar", "Pods / dorms / private rooms", "Free Wi-Fi", "Events programme"],
                "room_types": {"dorm_8bed": 22, "dorm_4bed_ensuite": 35, "private_double": 45},
                "reviews": {"tripadvisor_rating": 4.2, "highlights": ["best hostel in Amsterdam", "amazing social scene", "stylish design"]},
            },
        ],
        "restaurants": [
            {
                "name": "Rijks Restaurant",
                "cuisine": "Modern Dutch — inside the Rijksmuseum",
                "michelin": "1 star",
                "price_range": "$$$ (avg €65/person)",
                "address": "Museumstraat 2, 1071 XX Amsterdam",
                "opening_hours": "Lunch daily 12:00–15:00; Dinner Wed–Sun 18:00–22:00",
                "reservations": "Essential — book via rijksrestaurant.nl",
                "dietary": {"shellfish": "PRESENT — North Sea oysters, herring, prawns feature regularly; notify allergy", "vegetarian": "Full vegetarian tasting menu available"},
            },
            {
                "name": "De Kas",
                "cuisine": "Farm-to-table — greenhouse restaurant",
                "price_range": "$$$ (set lunch €49.50, set dinner €79.50)",
                "address": "Kamerlingh Onneslaan 3, 1097 DE Amsterdam",
                "opening_hours": "Mon–Fri 12:00–14:00 and 18:30–22:00; Sat 18:30–22:00",
                "notes": "Restaurant in a 1926 greenhouse. They grow most ingredients in the attached nursery. Extraordinary sustainable dining.",
                "dietary": {"vegetarian": "Set menu can be fully vegetarian on request", "shellfish": "Fish occasionally featured — ask on booking"},
            },
            {
                "name": "FEBO (Dutch fast food)",
                "cuisine": "Dutch snacks — kroket, frikandel, kaassoufflé",
                "price_range": "$ (€1.50–3.50)",
                "address": "Multiple locations across Amsterdam",
                "opening_hours": "24 hours",
                "dietary": {"shellfish": "None", "vegetarian": "Kaassoufflé (cheese) is vegetarian"},
                "notes": "Automat vending wall concept. Totally unique Dutch experience. Try the beef kroket.",
            },
        ],
        "attractions": [
            {
                "name": "Anne Frank House",
                "type": "Historic museum",
                "entry_usd": 18,
                "address": "Westermarkt 20, 1016 GV Amsterdam",
                "opening_hours": "Daily 09:00–22:00 (Apr–Oct); 09:00–19:00 (Nov–Mar)",
                "highlights": ["The actual hiding annex where Anne Frank wrote her diary", "Original diary manuscripts on display", "Deeply moving 1-hr audio guide"],
                "tips": ["SOLD OUT weeks ahead — book ONLINE ONLY (no door tickets)", "Silent and reflective — no large bags allowed"],
                "duration_recommended_hrs": 1.5,
                "booking_url": "https://www.annefrank.org/en/museum/tickets/",
            },
            {
                "name": "Rijksmuseum",
                "type": "National art museum",
                "entry_usd": 25,
                "address": "Museumstraat 1, 1071 XX Amsterdam",
                "opening_hours": "Daily 09:00–17:00",
                "highlights": ["Rembrandt's Night Watch (largest painting in museum)", "Vermeer collection (including The Milkmaid)", "Delft Blue collection", "Beautiful garden (free entry)"],
                "tips": ["Book timed entry online", "The museum is massive — focus on the Golden Age (1600s) floor", "Audio guide recommended"],
                "duration_recommended_hrs": 3,
            },
            {
                "name": "Canal Cruise",
                "type": "Boat tour",
                "entry_usd": 18,
                "highlights": ["See the 17th-century grachtengordes (canal belt) from water", "Evening cruises with wine €28", "Private boat hire from €120/hr"],
                "tips": ["Open boat recommended in summer", "Hop-on-hop-off cruises go past Anne Frank House, Rijksmuseum, Vondelpark"],
            },
        ],
    },

    # ── GERMANY / BERLIN ──────────────────────────────────────────────────
    "berlin": {
        "hotels": [
            {
                "name": "Hotel Adlon Kempinski",
                "stars": 5, "price_per_night_usd": 480,
                "area": "Mitte — next to Brandenburg Gate",
                "address": "Unter den Linden 77, 10117 Berlin",
                "amenities": ["Spa", "Two restaurants (1 Michelin-starred Lorenz Adlon Esszimmer)", "Pool", "Quintessential Berlin landmark", "Free Wi-Fi"],
                "room_types": {"classic": 480, "deluxe_brandenburg_gate_view": 650, "suite": 1200},
                "reviews": {"tripadvisor_rating": 4.7, "highlights": ["unparalleled location", "best service in Berlin", "historic grandeur"]},
                "notes": "Michael Jackson famously dangled his baby from a balcony here (2002). Right by Brandenburg Gate and Reichstag.",
            },
            {
                "name": "25hours Hotel Bikini Berlin",
                "stars": 4, "price_per_night_usd": 175,
                "area": "Charlottenburg — West Berlin, Zoological Garden",
                "address": "Budapester Straße 40, 10787 Berlin",
                "amenities": ["Monkey Bar rooftop (zoo views)", "Neni Restaurant", "Hammam spa", "Bikes to rent", "Free Wi-Fi", "Unique urban jungle design"],
                "room_types": {"compact": 175, "urban_jungle_room": 210, "suite": 380},
                "reviews": {"tripadvisor_rating": 4.5, "highlights": ["best rooftop bar in Berlin", "cool design hotel", "amazing zoo & city views"]},
            },
            {
                "name": "Generator Berlin Mitte",
                "stars": 3, "price_per_night_usd": 40,
                "area": "Mitte — walking distance to Hackescher Markt",
                "amenities": ["Bar", "Free Wi-Fi", "Self-service kitchen", "24-hr reception"],
                "room_types": {"dorm_8bed": 20, "private_double": 40},
                "reviews": {"tripadvisor_rating": 4.3},
            },
        ],
        "restaurants": [
            {
                "name": "Lorenz Adlon Esszimmer",
                "cuisine": "Modern European fine dining",
                "michelin": "2 stars",
                "price_range": "$$$$ (tasting menu €195–250)",
                "address": "Unter den Linden 77, 10117 Berlin (Hotel Adlon)",
                "opening_hours": "Tue–Sat 18:30–22:30",
                "reservations": "Essential — months in advance for weekend",
                "dietary": {"shellfish": "PRESENT", "vegetarian": "Vegetarian tasting menu available on request"},
            },
            {
                "name": "Mustafa's Gemüse Kebap",
                "cuisine": "Turkish dürüm / döner kebab",
                "price_range": "$ (€4.50)",
                "address": "Mehringdamm 32, 10961 Berlin (Kreuzberg)",
                "opening_hours": "Mon–Thu 10:00–02:00; Fri–Sat until 04:00",
                "dietary": {"shellfish": "None", "vegetarian": "Vegetarian dürüm available"},
                "notes": "Best döner in Berlin, possibly the world. Queue 45 min on weekends but 100% worth it. Famously topped with roasted vegetables.",
            },
            {
                "name": "Nobelhart und Schmutzig",
                "cuisine": "Brutal Localism — hyper-regional Berlin tasting menu",
                "michelin": "1 star",
                "price_range": "$$$ (tasting menu €119)",
                "address": "Friedrichstraße 218, 10969 Berlin",
                "opening_hours": "Tue–Sat from 18:30",
                "dietary": {"shellfish": "Ask at booking — menu changes", "vegetarian": "Not typically available; philosophy is around local Brandenburg produce"},
            },
        ],
        "attractions": [
            {
                "name": "Brandenburg Gate",
                "type": "Historic landmark",
                "entry_usd": 0,
                "address": "Pariser Platz, 10117 Berlin",
                "opening_hours": "Always open (outdoor)",
                "highlights": ["Symbol of German reunification", "Quadriga sculpture at top", "Spectacular at night when lit up"],
                "tips": ["Best photos from Pariser Platz side at golden hour", "Holocaust Memorial 3 min walk south"],
                "duration_recommended_hrs": 0.5,
            },
            {
                "name": "Topography of Terror",
                "type": "Historical documentation centre",
                "entry_usd": 0,
                "address": "Niederkirchnerstraße 8, 10963 Berlin",
                "opening_hours": "Daily 10:00–20:00",
                "highlights": ["Built on former Gestapo and SS HQ site", "Remaining Berlin Wall segment on-site", "Comprehensive outdoor exhibition free to walk"],
                "duration_recommended_hrs": 2,
            },
            {
                "name": "East Side Gallery",
                "type": "Outdoor mural art gallery on Berlin Wall",
                "entry_usd": 0,
                "address": "Mühlenstraße 3-100, 10243 Berlin (Friedrichshain)",
                "opening_hours": "Always open",
                "highlights": ["1.3 km longest remaining Berlin Wall section", "105 murals by international artists", "Includes Brezhnev–Honecker kiss painting"],
                "tips": ["Walk the full length from Ostbahnhof to Oberbaumbrücke", "Combine with Oberbaumbrücke photo"],
                "duration_recommended_hrs": 1.5,
            },
        ],
    },

    # ── DEHRADUN ──────────────────────────────────────────────────────────
    "dehradun": {
        "hotels": [
            {
                "name": "Lemon Tree Hotel Dehradun",
                "stars": 4, "price_per_night_usd": 58,
                "area": "Rajpur Road — main commercial strip",
                "address": "22/3 Rajpur Road, Dehradun, Uttarakhand 248001",
                "amenities": ["Rooftop pool", "Restaurant", "Free Wi-Fi", "Gym", "Parking", "Airport pickup ₹600"],
                "room_types": {"standard": 58, "deluxe": 72, "suite": 120},
                "reviews": {"tripadvisor_rating": 4.4, "highlights": ["best pool in Dehradun", "modern property", "good location"]},
                "cancellation_policy": "Free cancellation 24h before check-in.",
                "notes": "Best mid-range option in Dehradun city; 20 min from Jolly Grant Airport.",
            },
            {
                "name": "Moustache Hostel Dehradun",
                "stars": 2, "price_per_night_usd": 12,
                "area": "Near ISBT (Inter-State Bus Terminal)",
                "amenities": ["Free breakfast", "Free Wi-Fi", "Common room", "Bonfire (winter)", "Bicycle rent ₹200/day"],
                "room_types": {"dorm_6bed": 7, "private_double": 12},
                "reviews": {"tripadvisor_rating": 4.6, "highlights": ["best hostel in Uttarakhand", "incredible community", "amazing staff called 'Moustache family'"]},
                "notes": "Gateway for treks to Kedarnath, Chopta, Valley of Flowers. Excellent trek booking service from hostel.",
            },
            {
                "name": "The Vibrant Hotel and Spa",
                "stars": 3, "price_per_night_usd": 42,
                "area": "Doon Valley outskirts — peaceful, garden views",
                "amenities": ["Spa and Ayurvedic treatments", "Swimming pool", "Free Wi-Fi", "Valley views"],
                "reviews": {"tripadvisor_rating": 4.3},
                "notes": "Near Forest Research Institute (FRI) and Clock Tower area.",
            },
        ],
        "restaurants": [
            {
                "name": "Kumar Sweets & Restaurant",
                "cuisine": "North Indian thali / mithai",
                "price_range": "$ (thali ₹150 / ~$1.80)",
                "address": "Paltan Bazaar, Dehradun",
                "opening_hours": "Daily 08:00–22:00",
                "dietary": {"shellfish": "None", "vegetarian": "Fully vegetarian"},
                "notes": "Institution for over 60 years. Try the bal mithai (Kumaoni sweet) and kachori.",
            },
            {
                "name": "Barista Café",
                "cuisine": "Café / continental",
                "price_range": "$ (coffee ₹120–200)",
                "address": "Rajpur Road, Dehradun",
                "dietary": {"shellfish": "None", "vegetarian": "Fully vegetarian / vegan options"},
            },
            {
                "name": "Pal Dhaba",
                "cuisine": "North Indian highway dhaba",
                "price_range": "$ (meal ₹200–350)",
                "address": "National Highway 72, outskirts of Dehradun",
                "dietary": {"shellfish": "None", "vegetarian": "Dal makhani, paneer options always available"},
                "notes": "Best dal makhani in the region; truckers' dhaba with legendary butter roti.",
            },
        ],
        "attractions": [
            {
                "name": "Robbers Cave (Gucchupani)",
                "type": "Natural cave and stream",
                "entry_usd": 1,
                "address": "Anawala Village, Raipur Road, Dehradun",
                "opening_hours": "Daily 08:00–17:00",
                "highlights": ["Stream flows through natural cave", "Wading through ankle-to-knee-deep cold water inside cave", "Picnic area outside"],
                "duration_recommended_hrs": 2,
            },
            {
                "name": "Forest Research Institute (FRI)",
                "type": "Colonial heritage building and museum",
                "entry_usd": 1,
                "address": "FRI Campus, Dehradun, Uttarakhand 248006",
                "opening_hours": "Mon–Fri 09:00–17:00",
                "highlights": ["Massive 1929 Greco-Roman architecture", "6 museums covering Indian forests, timber, social forestry", "250-acre deer park grounds"],
                "duration_recommended_hrs": 3,
            },
            {
                "name": "Sahastradhara (Thousand-fold Spring)",
                "type": "Sulphur springs / waterfall",
                "entry_usd": 1,
                "address": "Sahastradhara Road, Dehradun",
                "opening_hours": "Daily 08:00–18:00",
                "highlights": ["Sulphur springs believed to have medicinal properties", "Cable car (₹150 one way)", "Cold cave bathing pools"],
                "notes": "Crowded on weekends; go on a weekday morning.",
            },
        ],
    },

    # ── MANALI / HIMACHAL PRADESH ──────────────────────────────────────────
    "manali": {
        "hotels": [
            {
                "name": "Span Resort & Spa",
                "stars": 5, "price_per_night_usd": 180,
                "area": "Kullu Valley — on the banks of Beas River, 12 km before Manali",
                "address": "NH-3, Katrain, Kullu, Himachal Pradesh 175129",
                "amenities": ["Heated outdoor pool (heated to 30°C even in Dec)", "Full-service spa", "Beas River-facing rooms", "Apple orchard walks", "Free Wi-Fi", "24-hr in-room dining"],
                "room_types": {"river_view_cottage": 180, "river_cottage_premium": 230, "suite": 380},
                "reviews": {"tripadvisor_rating": 4.6, "highlights": ["most beautiful setting in Kullu–Manali valley", "spa is exceptional", "heated pool in December is magical"]},
                "cancellation_policy": "Free cancellation 72h before arrival.",
                "notes": "40 min south of Manali town; good base for Solang Valley and Rohtang Pass. Accessible by private car.",
            },
            {
                "name": "Drifters Inn",
                "stars": 2, "price_per_night_usd": 22,
                "area": "Old Manali — backpacker hub",
                "address": "Old Manali Road, Manali, Himachal Pradesh 175131",
                "amenities": ["Rooftop café with Himalayan views", "Free Wi-Fi", "Common room with bonfire", "Laundry service ₹100/load", "Trek booking assistance"],
                "room_types": {"dorm_8bed": 8, "private_double": 22, "private_triple_balcony": 32},
                "reviews": {"tripadvisor_rating": 4.5, "highlights": ["best budget stay in Manali", "stunning mountain views from rooftop", "amazing community of travellers"]},
                "notes": "Heart of Old Manali village; surrounded by cafés, reggae joints, and trek outfitters.",
            },
            {
                "name": "Manu Allaya Resort",
                "stars": 4, "price_per_night_usd": 95,
                "area": "Central Manali — on the Mall Road",
                "address": "The Mall Road, Manali, Himachal Pradesh 175131",
                "amenities": ["Mountain views", "Indoor heated pool", "Restaurant (Himachali and continental cuisine)", "Free Wi-Fi", "Bonfire evenings"],
                "room_types": {"standard": 95, "deluxe_mountain_view": 130, "suite": 200},
                "reviews": {"tripadvisor_rating": 4.4},
            },
        ],
        "restaurants": [
            {
                "name": "Johnson's Café",
                "cuisine": "Continental and Himachali",
                "price_range": "$$ (meal ₹600–900)",
                "address": "Circuit House Road, Manali",
                "opening_hours": "Daily 08:00–22:00",
                "dietary": {"shellfish": "None", "vegetarian": "Extensive vegetarian menu"},
                "notes": "Most famous restaurant in Manali for 30+ years. Apple crumble dessert is legendary.",
            },
            {
                "name": "Drifters Café",
                "cuisine": "Multi-cuisine backpacker café",
                "price_range": "$ (meal ₹200–450)",
                "address": "Old Manali",
                "dietary": {"shellfish": "None", "vegetarian": "Extensive vegan and vegetarian options"},
                "notes": "Hash browns, Israeli salads, pasta, Tibetan momos — the classic Old Manali travellers' menu.",
            },
            {
                "name": "Lazy Dog Lounge",
                "cuisine": "Snacks, cocktails, bonfire nights",
                "price_range": "$ (cocktails ₹350–600)",
                "address": "Old Manali",
                "notes": "Best sunset views from the terrace. Live music Thursday and Saturday evenings.",
                "dietary": {"shellfish": "None", "vegetarian": "Good options"},
            },
        ],
        "attractions": [
            {
                "name": "Solang Valley",
                "type": "Adventure valley — skiing (winter) / paragliding (summer)",
                "entry_usd": 0,
                "distance_from_manali_km": 14,
                "activities": {
                    "winter_nov_mar": ["skiing (equipment hire ₹500/hr)", "snowboarding", "snow zorbing ₹200/ride"],
                    "summer_apr_oct": ["paragliding (₹2500 tandem flight)", "zorbing", "ATV rides"],
                },
                "tips": ["Hire a taxi from Manali ₹800 return; shared cab ₹200", "Go on weekdays to avoid Delhi crowds"],
                "duration_recommended_hrs": 4,
            },
            {
                "name": "Rohtang Pass",
                "type": "High-altitude mountain pass",
                "entry_usd": 5,
                "altitude_m": 3978,
                "distance_from_manali_km": 51,
                "opening_months": "June–October (closed in winter and during BRO maintenance days)",
                "highlights": ["Panoramic Himalayan views at 4000m", "Gateway to Lahaul-Spiti", "Snow even in June (check conditions)"],
                "permits": "Online permit required from Himachal Pradesh tourism (₹500, available at rotangpass.hp.gov.in); only 800 vehicles/day allowed",
                "tips": ["Rent warm clothing in Manali market (₹200/day) — it's cold at top regardless of season", "Hire a Jeep/SUV only (not cars)"],
                "duration_recommended_hrs": 8,
            },
            {
                "name": "Hadimba Temple (Dhungri Temple)",
                "type": "Hindu temple — 1553 CE",
                "entry_usd": 0,
                "address": "Hadimba Temple Road, Manali",
                "opening_hours": "Daily 08:00–20:00",
                "highlights": ["Four-tiered pagoda woodcraft architecture", "Deodar cedar forest surrounds", "Genuine Himalayan village atmosphere"],
                "duration_recommended_hrs": 1,
            },
        ],
    },

    # ── DELHI ─────────────────────────────────────────────────────────────
    "delhi": {
        "hotels": [
            {
                "name": "The Leela Palace New Delhi",
                "stars": 5, "price_per_night_usd": 380,
                "area": "Diplomatic Enclave, Chanakyapuri",
                "address": "Diplomatic Enclave, Chanakyapuri, New Delhi 110023",
                "amenities": ["Spa by ESPA", "5 restaurants including Jamavar (Michelin Bib Gourmand)", "Rooftop bar", "Heated pool", "Butler service", "Free Wi-Fi"],
                "room_types": {"royal_room": 380, "premier_room_garden": 470, "suite": 900},
                "reviews": {"tripadvisor_rating": 4.8, "highlights": ["best hotel in Delhi", "extraordinary dining", "impeccable service"]},
                "cancellation_policy": "72h free cancellation.",
            },
            {
                "name": "Zostel Delhi",
                "stars": 2, "price_per_night_usd": 10,
                "area": "Paharganj — backpacker district near New Delhi Railway Station",
                "address": "4771 Arakashan Road, Ram Nagar, Paharganj, New Delhi 110055",
                "amenities": ["Free Wi-Fi", "Common room", "Travel desk", "Free breakfast (basic)", "Laundry service"],
                "room_types": {"dorm_8bed": 6, "private_double": 10},
                "reviews": {"tripadvisor_rating": 4.4, "highlights": ["amazing social atmosphere", "unbeatable Delhi location", "great staff for recommendations"]},
                "notes": "Flagship Zostel property; very lively and social. Ideal for solo travellers.",
            },
        ],
        "restaurants": [
            {
                "name": "Karim's (Old Delhi)",
                "cuisine": "Mughlai — kebabs, nihari, biryani",
                "price_range": "$ (meal ₹400–700)",
                "address": "16, Gali Kababian, Near Jama Masjid, Old Delhi 110006",
                "opening_hours": "Daily 09:00–00:00",
                "dietary": {"shellfish": "None", "vegetarian": "Limited — meat-heavy menu"},
                "notes": "Founded 1913. Serving Mughal-descended recipes for 100+ years. The mutton burra kebab and nihari are unmissable.",
            },
            {
                "name": "Bukhara (ITC Maurya Hotel)",
                "cuisine": "Frontier Indian — tandoor and kebabs",
                "michelin": "Not rated (India has no Michelin yet) — but considered by many India's best restaurant",
                "price_range": "$$$ (avg ₹3500 / ~$42 per person)",
                "address": "ITC Maurya, Sardar Patel Marg, Diplomatic Enclave, New Delhi",
                "dietary": {"shellfish": "None", "vegetarian": "Dal Bukhara (famous 18-hr black lentils) is vegetarian and extraordinary"},
                "notes": "Bill Clinton, Vladimir Putin, Barack Obama have all dined here. No cutlery — eat with hands by tradition.",
            },
        ],
        "attractions": [
            {
                "name": "Red Fort (Lal Qila)",
                "type": "UNESCO World Heritage Site — Mughal fort",
                "entry_usd": 10,
                "address": "Netaji Subhash Marg, Lal Qila, Chandni Chowk, New Delhi",
                "opening_hours": "Tue–Sun 09:30–16:30; closed Mon",
                "highlights": ["17th-century Mughal palace complex", "Sound-and-light show evenings (₹80)", "Diwan-i-Aam and Diwan-i-Khas audience halls"],
                "duration_recommended_hrs": 2,
            },
            {
                "name": "Chandni Chowk",
                "type": "Historic bazaar and street food market",
                "entry_usd": 0,
                "address": "Old Delhi, Delhi",
                "opening_hours": "Daily 10:00–20:00 (most stalls)",
                "highlights": ["1.5 km of silver jewellery, spices, textiles", "Paranthe Wali Gali — alley of stuffed parathas", "Jama Masjid (India's largest mosque) nearby"],
                "tips": ["Go on weekday morning; Sunday is busiest", "Hire a cycle-rickshaw (₹50 for 30-min tour)"],
            },
        ],
    },
}


def places_search(city: str, category: str = "hotels") -> dict:
    """
    Returns hotels / restaurants / attractions for a city.
    Large bloated payload covering full amenities, pricing, reviews, policies.
    """
    key = city.strip().lower()
    city_data = _PLACES_DB.get(key, {})

    if not city_data:
        for db_key in _PLACES_DB:
            if db_key in key or key in db_key:
                city_data = _PLACES_DB[db_key]
                key = db_key
                break

    if not city_data:
        return {
            "city": city,
            "category": category,
            "error": "No data for this city yet.",
            "available_cities": list(_PLACES_DB.keys()),
        }

    cat = category.strip().lower()
    results = city_data.get(cat, [])
    if not results:
        cat = "hotels"
        results = city_data.get("hotels", [])

    return {
        "city": key,
        "category": cat,
        "result_count": len(results),
        "results": results,
        "metadata": {
            "source": "mock_places_db_v1",
            "note": "Prices are indicative (Apr 2026). Always verify directly with venue.",
            "currency": "USD unless stated.",
        },
    }


SCHEMA: dict = {
    "type": "function",
    "function": {
        "name": "places_search",
        "description": (
            "Search for hotels, restaurants, or attractions in a specific city. "
            "Returns detailed listings with prices, reviews, amenities, and policies."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "description": "City name, e.g. 'Paris', 'Tokyo', 'Bali', 'Amsterdam', 'Berlin', 'Dehradun', 'Manali', 'Delhi'",
                },
                "category": {
                    "type": "string",
                    "enum": ["hotels", "restaurants", "attractions"],
                    "description": "What to search for",
                },
            },
            "required": ["city"],
        },
    },
}
